hbase:
 container_name: hbase
 hostname: hbase
 image: sixeyed/hbase-succinctly:2
 expose:
  - "2181"
  - "60000"
  - "60020"
 ports:
  - "60010:60010"
  - "60030:60030"

hive:
 container_name: hive
 hostname: hive
 image: sixeyed/hive-succinctly
 ports:
  - "8088:8088"
  - "8080:8888"
 links: 
  - hbase